### ISSUE TITLE
Error: Operation failed: BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 

### ISSUE THREAD

**Issue by leopucci** [marcelmaatkamp/docker-rabbitmq-mongodb#1]
I am getting error running this a docker conteiner.
For some reason it does not find the queue, but the queue exists in the server

`[Error: Operation failed: BasicConsume; 404 (NOT-FOUND) with message "NOT_FOUND - no queue 'TCP_TO_RABBIT_QUEUE_SERVER_01' in vhost '/'"]
`
```
rabbitmqtomongodb:
   image: marcelmaatkamp/rabbitmq-mongodb
   container_name: rabbitmqtomongodb
   restart: always
   environment:
     - AMQPHOST=amqp://admin:1111111@rabbitmq
     - MONGODB=mongodb://mongo/eeses:27018
     - MONGOCOLLECTION=gps
     - TRANSLATECONTENT=true
     - FORCECONTENTTYPE=application/json
   command: TCP_TO_RABBIT_QUEUE_SERVER_01
```
For some reason it does not work.
